import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL || 'https://davkthwggjegcqrmigaph.supabase.co';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

// Admin client (uses service role key) - for server-side operations
export const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false
  }
});

// Public client (uses anon key) - for client-facing operations
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Database types (will be auto-generated by Supabase CLI)
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          username: string;
          email: string;
          password: string;
          full_name: string;
          bio: string;
          avatar: string;
          is_private: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          username: string;
          email: string;
          password: string;
          full_name: string;
          bio?: string;
          avatar?: string;
          is_private?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          email?: string;
          password?: string;
          full_name?: string;
          bio?: string;
          avatar?: string;
          is_private?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      posts: {
        Row: {
          id: string;
          user_id: string;
          caption: string;
          location: string;
          type: string;
          images: any;
          videos: any;
          tags: any;
          mentions: any;
          filters: any;
          crop: any;
          sound: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          caption?: string;
          location?: string;
          type?: string;
          images?: any;
          videos?: any;
          tags?: any;
          mentions?: any;
          filters?: any;
          crop?: any;
          sound?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          caption?: string;
          location?: string;
          type?: string;
          images?: any;
          videos?: any;
          tags?: any;
          mentions?: any;
          filters?: any;
          crop?: any;
          sound?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
};

export default supabase;

